import Link from "next/link";
import { useSession } from "next-auth/react";
import Head from "next/head";

import { api } from "~/utils/api";

const Characters = () => {
  const session = useSession();
  const currentUser = session.data?.user;

  // Get all games a user is in.
  const characters = api.character.getCharactersOfUser.useQuery({
    userId: currentUser?.id ?? "",
  });

  // Remove character
  const removeUser = api.character.deleteCharacter.useMutation();

  // Delete game
  const handleOnDelete = (e: React.MouseEvent, id: string) => {
    removeUser.mutate({ characterId: id });
    characters.refetch();
  };

  return (
    <>
      <Head>
        <title>DND map</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-600">
        <h1>Active games</h1>
        {/* Get API call for all games where user */}
        {characters?.data && characters.data.length > 0 ? (
          <ul>
            {characters.data.map((character) => {
              return (
                <div key={character.characterId}>
                  <li className="mb-3 grid grid-cols-3 gap-4">
                    {<img src={character.imgSrc}></img>}
                    {character.name}

                    {game.game.dungeonMasterId === currentUser?.id && (
                      <button
                        onClick={(e) => handleOnDelete(e, game.game.gameId)}
                      >
                        Delete character
                      </button>
                    )}
                  </li>
                </div>
              );
            })}
          </ul>
        ) : (
          <h2> No active games found. </h2>
        )}

        <Link href="/">Go back</Link>
      </main>
    </>
  );
};

export default Characters;
