import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  const session = useSession();
  const user = session.data?.user;

  return (
    <>
      <Head>
        <title>DND map</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-600">
        {user != null ? (
          <>
            <h1>{`Welcome ${user.name}`}</h1>
            <ul>
              <li>
                <Link href="/new-game">Start new game</Link>
              </li>
              <li>
                <Link href="/active-games">See active games</Link>
              </li>
              <li>
                <Link href="/create-character">Create character</Link>
              </li>
              <li>
                <Link href="/characters">Characters</Link>
              </li>
            </ul>
            <button onClick={() => void signOut()}>Log out</button>
          </>
        ) : (
          <>
            <button onClick={() => void signIn()}>Log in</button>
          </>
        )}
      </main>
    </>
  );
}
