import Link from "next/link";
import Head from "next/head";
import React, {
  MouseEvent as ReactMouseEvent,
  useEffect,
  useState,
} from "react";
import { api } from "~/utils/api";

const NewGame = () => {
  const [players, setPlayers] = useState<string[]>([]);
  const [input, setInput] = useState("");
  const [border, setBorder] = useState({ color: "black", size: 1 });
  const [errorText, setErrorText] = useState("");
  const getUser = api.user.getAll.useQuery({ userName: input });

  const handleOnAddPlayer = (e: ReactMouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    if (
      !getUser.data ||
      getUser.data.length === 0 ||
      // Verify username exists in database
      players.includes(getUser.data[0]?.name as string)
    ) {
      setBorder({ color: "rose-500", size: 2 });
      setErrorText("Username not found, try again.");
      return;
    }

    setPlayers((prev) => [...prev, input]);
    setBorder({ color: "black", size: 1 });
    setErrorText("");
    setInput("");
  };

  const handleOnAddMap = (e: ReactMouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
  };

  const handleOnChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInput(e.target.value);
  };

  return (
    <>
      <Head>
        <title>DND map</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col  items-center justify-center bg-slate-600">
        <h1>Starting?</h1>
        <form>
          <label>Select map</label>
          <div>MAP PREVIEW</div>
          <button onClick={handleOnAddMap}>Add player</button>
          <input
            type="text"
            id="map"
            name="map"
            placeholder="Enter image url"
          ></input>
          <br></br>
          <label>Invite players</label>
          <div>
            {players.length > 0 &&
              players.map((player) => {
                return <p key={players.indexOf(player)}>Player 1: {player}</p>;
              })}
            <input
              type="text"
              className={`border-${border.size} border-${border.color}`}
              value={input || ""}
              onChange={handleOnChange}
            ></input>
            {errorText && <p>{errorText}</p>}

            <button onClick={handleOnAddPlayer}>Add player</button>
          </div>

          {/* <ul>
            <li>Invite players</li>
            <li>Place characters</li>
            <li>Start game</li>
          </ul> */}
        </form>
        <button>Add NPCs</button>
        <Link href="/">Go back</Link>
      </main>
    </>
  );
};

export default NewGame;
